name: gpcapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+4      # ğŸ“¸ Para usar la cÃ¡mara
  mobile_scanner: ^3.2.0 # ğŸ“¡ Para escanear cÃ³digos QR
  go_router: ^6.0.0 # ğŸš€ Para navegaciÃ³n
  flutter_riverpod: ^2.0.0 # ğŸ› ï¸ Para manejar estados
  flutter_secure_storage: ^8.0.0
  http: ^1.3.0
  shared_preferences: ^2.5.2
  pointycastle: 3.9.1                       
  encrypt: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/background.png

